// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'infrastructure/storage/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7458871411463573368),
      name: 'ChatMessageEntity',
      lastPropertyId: const obx_int.IdUid(7, 3873964652748130017),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1956111505892853562),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4156066204207142179),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7956142709383740204),
            name: 'role',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4797666192326777968),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8405762128786076914),
            name: 'estimatedTokens',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1090035181450707871),
            name: 'estimatedCost',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3873964652748130017),
            name: 'sessionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 3643020334604267465),
            relationTarget: 'ChatSessionEntity')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4219731854516186011),
      name: 'ChatSessionEntity',
      lastPropertyId: const obx_int.IdUid(5, 8952544034938923350),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1762263540956521470),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2127559019745157922),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6930892090358354320),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7345138939472983851),
            name: 'selectedModel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8952544034938923350),
            name: 'selectedProvider',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'messages',
            srcEntity: 'ChatMessageEntity',
            srcField: 'session')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7277343937576684152),
      name: 'AppSettingsEntity',
      lastPropertyId: const obx_int.IdUid(3, 265515768545759117),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4775809739107013484),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2751849935647987923),
            name: 'budgetLimit',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 265515768545759117),
            name: 'blockOnLimit',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 7277343937576684152),
      lastIndexId: const obx_int.IdUid(1, 3643020334604267465),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
        model: _entities[0],
        toOneRelations: (ChatMessageEntity object) => [object.session],
        toManyRelations: (ChatMessageEntity object) => {},
        getId: (ChatMessageEntity object) => object.id,
        setId: (ChatMessageEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          final roleOffset = fbb.writeString(object.role);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contentOffset);
          fbb.addOffset(2, roleOffset);
          fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
          fbb.addInt64(4, object.estimatedTokens);
          fbb.addFloat64(5, object.estimatedCost);
          fbb.addInt64(6, object.session.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final roleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final timestampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final estimatedTokensParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final estimatedCostParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final object = ChatMessageEntity(
              content: contentParam,
              role: roleParam,
              timestamp: timestampParam,
              estimatedTokens: estimatedTokensParam,
              estimatedCost: estimatedCostParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.session.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.session.attach(store);
          return object;
        }),
    ChatSessionEntity: obx_int.EntityDefinition<ChatSessionEntity>(
        model: _entities[1],
        toOneRelations: (ChatSessionEntity object) => [],
        toManyRelations: (ChatSessionEntity object) => {
              obx_int.RelInfo<ChatMessageEntity>.toOneBacklink(7, object.id,
                      (ChatMessageEntity srcObject) => srcObject.session):
                  object.messages
            },
        getId: (ChatSessionEntity object) => object.id,
        setId: (ChatSessionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ChatSessionEntity object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final selectedModelOffset = fbb.writeString(object.selectedModel);
          final selectedProviderOffset =
              fbb.writeString(object.selectedProvider);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(3, selectedModelOffset);
          fbb.addOffset(4, selectedProviderOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final selectedModelParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final selectedProviderParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final object = ChatSessionEntity(
              title: titleParam,
              createdAt: createdAtParam,
              selectedModel: selectedModelParam,
              selectedProvider: selectedProviderParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<ChatSessionEntity>(
              object.messages,
              store,
              obx_int.RelInfo<ChatMessageEntity>.toOneBacklink(7, object.id,
                  (ChatMessageEntity srcObject) => srcObject.session));
          return object;
        }),
    AppSettingsEntity: obx_int.EntityDefinition<AppSettingsEntity>(
        model: _entities[2],
        toOneRelations: (AppSettingsEntity object) => [],
        toManyRelations: (AppSettingsEntity object) => {},
        getId: (AppSettingsEntity object) => object.id,
        setId: (AppSettingsEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AppSettingsEntity object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.budgetLimit);
          fbb.addBool(2, object.blockOnLimit);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final budgetLimitParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final blockOnLimitParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final object = AppSettingsEntity(
              budgetLimit: budgetLimitParam, blockOnLimit: blockOnLimitParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// see [ChatMessageEntity.id]
  static final id =
      obx.QueryIntegerProperty<ChatMessageEntity>(_entities[0].properties[0]);

  /// see [ChatMessageEntity.content]
  static final content =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[0].properties[1]);

  /// see [ChatMessageEntity.role]
  static final role =
      obx.QueryStringProperty<ChatMessageEntity>(_entities[0].properties[2]);

  /// see [ChatMessageEntity.timestamp]
  static final timestamp =
      obx.QueryDateProperty<ChatMessageEntity>(_entities[0].properties[3]);

  /// see [ChatMessageEntity.estimatedTokens]
  static final estimatedTokens =
      obx.QueryIntegerProperty<ChatMessageEntity>(_entities[0].properties[4]);

  /// see [ChatMessageEntity.estimatedCost]
  static final estimatedCost =
      obx.QueryDoubleProperty<ChatMessageEntity>(_entities[0].properties[5]);

  /// see [ChatMessageEntity.session]
  static final session =
      obx.QueryRelationToOne<ChatMessageEntity, ChatSessionEntity>(
          _entities[0].properties[6]);
}

/// [ChatSessionEntity] entity fields to define ObjectBox queries.
class ChatSessionEntity_ {
  /// see [ChatSessionEntity.id]
  static final id =
      obx.QueryIntegerProperty<ChatSessionEntity>(_entities[1].properties[0]);

  /// see [ChatSessionEntity.title]
  static final title =
      obx.QueryStringProperty<ChatSessionEntity>(_entities[1].properties[1]);

  /// see [ChatSessionEntity.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ChatSessionEntity>(_entities[1].properties[2]);

  /// see [ChatSessionEntity.selectedModel]
  static final selectedModel =
      obx.QueryStringProperty<ChatSessionEntity>(_entities[1].properties[3]);

  /// see [ChatSessionEntity.selectedProvider]
  static final selectedProvider =
      obx.QueryStringProperty<ChatSessionEntity>(_entities[1].properties[4]);

  /// see [ChatSessionEntity.messages]
  static final messages =
      obx.QueryBacklinkToMany<ChatMessageEntity, ChatSessionEntity>(
          ChatMessageEntity_.session);
}

/// [AppSettingsEntity] entity fields to define ObjectBox queries.
class AppSettingsEntity_ {
  /// see [AppSettingsEntity.id]
  static final id =
      obx.QueryIntegerProperty<AppSettingsEntity>(_entities[2].properties[0]);

  /// see [AppSettingsEntity.budgetLimit]
  static final budgetLimit =
      obx.QueryDoubleProperty<AppSettingsEntity>(_entities[2].properties[1]);

  /// see [AppSettingsEntity.blockOnLimit]
  static final blockOnLimit =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[2].properties[2]);
}
